### ISSUE TITLE
Plans for a Vue 3 Version?

### ISSUE THREAD

**Issue by majortom64** [marverix/v-tostini#22]
I found this on Awesome Vue and it seems like exactly what I want (plan to use it with a Tailwind notification). Was wondering if you had plans to update it to Vue 3 anytime soon? I am new to Vue (and JS in general), so I am not sure I can provide much help. I will come back with any specific problems I find (and if I can solve any of them), a PR. :-)

**Comment by marverix** [comment]
Hey @majortom64 ! 
I don't think that I will support Vue 3. Vue 3 totally changed the way of creating components :( I have no time to learn totally new framework (because Vue 2 and Vue 3 are really different in my opinion)... So I will stick with Vue 2, which is really good framework in my opinion. Ofc they will force users to use new version, but this does not change the fact... that a lot of people hates Vue 3 :( 
https://www.reddit.com/r/vuejs/comments/c319el/vue_3_will_change_vue_in_a_big_way_current_syntax/
But if you have time, then please either feel free to fork this repo and rename to v-tostini-3 or something like this, or we can create separate branch for it.
